
spring:
  application:
    name: ead-course-service
  config:
    #    import: 'optional:configserver:' para quando o config server nao estiver ativo
    import: 'configserver:'
  cloud:
    config:
      discovery:
        service-id: ead-config-server
      username: configserver
      password: 'ead123cs'
